# Generated by Django 4.0.6 on 2022-08-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_name_neighborhood_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='população',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
