# Generated by Django 4.0.6 on 2022-08-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_neighborhood_população'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='população',
            new_name='populacao',
        ),
    ]
