# Generated by Django 4.0.6 on 2022-08-10 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='employer',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2022, 8, 10, 17, 38, 25, 755312)),
        ),
    ]
