# Generated by Django 4.0.6 on 2022-08-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_employer_id_alter_employer_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
